name: "local-dev"

networks:

    local-dev:
        name: "local-dev"
        driver: "bridge"

volumes:

    local-dev.storage.mssql:
        name: "local-dev.storage.mssql"
        
    local-dev.storage.mongodb-data:
        name: "local-dev.storage.mongodb-data"
    local-dev.storage.mongodb-config:
        name: "local-dev.storage.mongodb-config"
        
    local-dev.storage.rabbitmq:
        name: "local-dev.storage.rabbitmq"

services:

    storage.mssql:
        image: "mcr.microsoft.com/mssql/server:2025-CU4-ubuntu-24.04"
        container_name: "local-dev.storage.mssql"
        environment:
            - "ACCEPT_EULA=Y"
            - "MSSQL_PID=${STORAGE_MSSQL_PID}"
            - "MSSQL_SA_PASSWORD=${STORAGE_MSSQL_PASSWORD}"
        volumes:
            #- "./volumes/mssql-data:/var/opt/mssql" #need ext4
            - "local-dev.storage.mssql:/var/opt/mssql"
        ports:
            - "${STORAGE_MSSQL_PORT}:1433"
        networks:
            - "local-dev"
        deploy:
            resources:
                limits:
                    memory: "2G"

    storage.mongodb:
        image: "mongodb/mongodb-community-server:8.3.1-ubi9-slim"
        container_name: "local-dev.storage.mongodb"
        environment:
            - "MONGODB_INITDB_ROOT_USERNAME=${STORAGE_MONGODB_USER}"
            - "MONGODB_INITDB_ROOT_PASSWORD=${STORAGE_MONGODB_PASSWORD}"
        volumes:
            #- "./volumes/mongodb-data:/data/db"
            #- "./volumes/mongodb-config:/data/configdb"
            - "local-dev.storage.mongodb-data:/data/db"
            - "local-dev.storage.mongodb-config:/data/configdb"
        ports:
            - "${STORAGE_MONGODB_PORT}:27017"
        networks:
            - "local-dev"
        deploy:
            resources:
                limits:
                    memory: "1G"

    storage.rabbitmq:
        image: "rabbitmq:4.3.0-management-alpine"
        container_name: "local-dev.storage.rabbitmq"
        environment:
            - "RABBITMQ_DEFAULT_USER=${STORAGE_RABBITMQ_USER}"
            - "RABBITMQ_DEFAULT_PASS=${STORAGE_RABBITMQ_PASSWORD}"
            - "RABBITMQ_CLUSTER_NAME=local-dev"
            - "RABBITMQ_NODENAME=local-dev-node-1"
            - "RABBITMQ_ERLANG_COOKIE=secret-rabbitmq-cookie"
        volumes:
            #- "./volumes/rabbitmq:/var/lib/rabbitmq"
            - "local-dev.storage.rabbitmq:/var/lib/rabbitmq"
        ports:
            - "${STORAGE_RABBITMQ_AMQP_PORT}:5672"
            - "${STORAGE_RABBITMQ_HTTP_PORT}:15672"
        networks:
            - "local-dev"
        deploy:
            resources:
                limits:
                    memory: "512M"